<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="sk" lang="sk">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>{block #title}Nette Patients{/block}</title>
  <link rel="stylesheet" href="{$basePath}/css/main.css" type="text/css" media="screen, projection, tv" />
</head>

<body>
<div id="wrapper">

  <div id="header">
    <a id="homelink" href="{$baseUri}">Nette Patients<span></span></a>
  </div><!-- #header -->


  <div id="content">
    {foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}
    {include #content}
  </div><!-- #content -->


  <div id="footer">
    <p>Copyright &copy;2010 Igor Hlina</p>
  </div><!-- #footer -->

</div><!-- #wrapper -->
</body>
</html>
